In [1]:
import numpy as np
import os
import glob
import PIL
import PIL.Image
import tensorflow as tf
import tensorflow_datasets as tfds
import collections
from sklearn.model_selection import train_test_split
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow_federated as tff
import random

In [2]:
dsdir = "C:/Users/temmuz/Desktop/2022-2/proje/stanford/dataset"
class_count = np.zeros((6,11))
for i in range(6):
    dsdiri = dsdir+"/"+str(i)
    for j in range(11):
        dsdirij = dsdiri+"/"+str(j)+'/*.jpg'
        class_count[i,j] += len(glob.glob(dsdirij))

In [68]:
class_count = class_count.astype(int)
class_count2 = np.copy(class_count)
class_count2[:,0] = class_count[:,0]*[0.1,0.1,0.1,0.1,0.5,0.1]
class_count2[:,1] = class_count[:,1]*2
class_count2[:,3] = class_count[:,3]*2
class_count2[:,4] = class_count[:,4]*6
class_count2[:,5] = class_count[:,5]*[0.1,0.1,0.1,0.1,0.7,0.1]
class_count2[:,6] = class_count[:,6]*15
class_count2[:,7] = class_count[:,7]*10
class_count2[:,8] = class_count[:,8]*4
class_count2[:,9] = class_count[:,9]*2
class_count2[:,10] = class_count[:,10]*3
class_count2 = class_count2.astype(int)

In [74]:
class_count

array([[5728,  641,    0,    0,    0, 3409,  127,  124,    0,    0,  298],
       [2686,  606, 6371,    0,    0, 4725,    0,    0,    0,  837,  489],
       [1406,  258,    0,    0,  607, 1098,    0,    0,    0,   25,  310],
       [5231, 1127,    0, 2033,    0, 3705,    0,    0,    0,  401,  771],
       [8684,  998,    0,  316,    0, 6582,    0,  202,    0,  514,  297],
       [5415,  220,    0,    0,  317, 2859,  113,   92,  874,    0,    0]])

In [70]:
class_count2

array([[ 572, 1282,    0,    0,    0,  340, 1905, 1240,    0,    0,  894],
       [ 268, 1212, 6371,    0,    0,  472,    0,    0,    0, 1674, 1467],
       [ 140,  516,    0,    0, 3642,  109,    0,    0,    0,   50,  930],
       [ 523, 2254,    0, 4066,    0,  370,    0,    0,    0,  802, 2313],
       [4342, 1996,    0,  632,    0, 4607,    0, 2020,    0, 1028,  891],
       [ 541,  440,    0,    0, 1902,  285, 1695,  920, 3496,    0,    0]])

In [71]:
sum(class_count2)

array([6386, 7700, 6371, 4698, 5544, 6183, 3600, 4180, 3496, 3554, 6495])

In [72]:
np.sum(class_count2,1)

array([ 6233, 11464,  5387, 10328, 15516,  9279])

In [27]:
sum(class_count2[1])

11111

In [28]:
class_count2[1]

array([ 537,  606, 6371,    0,    0,  945,    0,    0,    0, 1674,  978])

In [30]:
537+606+6371+945+1674+978

11111

In [73]:
np.sum(class_count2)

58207

In [39]:
np.argmax(class_count,1)

array([0, 2, 0, 0, 0, 0], dtype=int64)

In [40]:
class_count[:,0]

array([5728, 2686, 1406, 5231, 8684, 5415])

In [42]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [43]:
class_count[:,0]*a

array([ 5728,  5372,  4218, 20924, 43420, 32490])

In [77]:
class_count3 = np.zeros((3,11))
class_count3[0,:] = class_count[0,:]+class_count[2,:]+class_count[5,:]
class_count3[1,:] = class_count[1,:]+class_count[3,:]
class_count3[2,:] = class_count[4,:]
class_count3 = class_count3.astype(int)

In [79]:
class_count3

array([[12549,  1119,     0,     0,   924,  7366,   240,   216,   874,
           25,   608],
       [ 7917,  1733,  6371,  2033,     0,  8430,     0,     0,     0,
         1238,  1260],
       [ 8684,   998,     0,   316,     0,  6582,     0,   202,     0,
          514,   297]])

In [81]:
np.sum(class_count3,0)

array([29150,  3850,  6371,  2349,   924, 22378,   240,   418,   874,
        1777,  2165])

In [82]:
np.sum(class_count3,1)

array([23921, 28982, 17593])

In [109]:
class_count4 = np.copy(class_count3)
ratio0 = 0.2
ratio1 = [1,1,3]
ratio2 = 0.7
ratio3 = 2
ratio4 = 5
ratio5 = 0.2
ratio6 = 17
ratio7 = [10,10,15]
ratio8 = 5
ratio9 = [2,2,4]
ratio10 = [2,2,4]
class_count4[:,0] = class_count3[:,0]*ratio0
class_count4[:,1] = class_count3[:,1]*ratio1
class_count4[:,2] = class_count3[:,2]*ratio2
class_count4[:,3] = class_count3[:,3]*ratio3
class_count4[:,4] = class_count3[:,4]*ratio4
class_count4[:,5] = class_count3[:,5]*ratio5
class_count4[:,6] = class_count3[:,6]*ratio6
class_count4[:,7] = class_count3[:,7]*ratio7
class_count4[:,8] = class_count3[:,8]*ratio8
class_count4[:,9] = class_count3[:,9]*ratio9
class_count4[:,10] = class_count3[:,10]*ratio10

In [110]:
class_count4

array([[2509, 1119,    0,    0, 4620, 1473, 4080, 2160, 4370,   50, 1216],
       [1583, 1733, 4459, 4066,    0, 1686,    0,    0,    0, 2476, 2520],
       [1736, 2994,    0,  632,    0, 1316,    0, 3030,    0, 2056, 1188]])

In [111]:
np.sum(class_count4,0)

array([5828, 5846, 4459, 4698, 4620, 4475, 4080, 5190, 4370, 4582, 4924])

In [112]:
np.sum(class_count4,1)

array([21597, 18523, 12952])

In [104]:
240*17

4080